insert into election values (2,2,'2018-02-17','2018-02-24','2018-02-25','2018-02-28');

INSERT INTO position(electionTypeID, positionName, description) VALUES (2, 'President',"The president's job is to direct the Society and be the external representative. This involves maintaining relationships with the faculty, sponsors and other external sources, as well as chairing meetings within the Society. The President must keep track of every aspect of the Society to ensure the whole committee and all members are working towards the same goals.");
INSERT INTO position(electionTypeID, positionName, description) VALUES (2, 'Vice President',"The vice president assists the president in admin tasks and representing the society at faculty and SUSU society events.");
INSERT INTO position(electionTypeID, positionName, description) VALUES (2, 'Treasurer',"The treasurer is responsible for keeping all finances in order as they are responsible for the society's funds. They are also required to present the accounts at the AGM and any other time if required.");
INSERT INTO position(electionTypeID, positionName, description) VALUES (2, 'Academic Officer', "The academic secretary has the job of organising ECSS talks and academic events, raising sponsorship funds for the society, managing all interaction with all ECSS sponsors as well as looking out for new ones.");
INSERT INTO position(electionTypeID, positionName, description) VALUES (2, 'Welfare Officer',"The welfare officer caters for students in a personal manner by ensuring everyone is included in the society's activities. They also take care of the needs of students and their view of certain aspects like the push for releasing timetables earlier.");
INSERT INTO position(electionTypeID, positionName, description) VALUES (2, 'Secretary', "The secretary is in charge of taking minutes, organising the meetings and sorting through admin items for the society.");
INSERT INTO position(electionTypeID, positionName, description) VALUES (2, 'Games Officer', "The games officer is in charge of organising gaming events across the year, which mostly are social events where anyone can turn up and play any games with friends.");
INSERT INTO position(electionTypeID, positionName, description) VALUES (2, 'Social Secretary',"The social secretary is responsible for arranging social events for the Society, sufficiently varied to cater to as much of the membership as possible.");
INSERT INTO position(electionTypeID, positionName, description) VALUES (2, 'Web Officer',"The web officer is in charge of maintaining the society website and services, allowing the rest of the committee to get the latest information direct to you!");
INSERT INTO position(electionTypeID, positionName, description) VALUES (2, 'Marketing Officer',"The marketing officer produces advertising media for the society. These includes emails, posters and any other required material.");
INSERT INTO position(electionTypeID, positionName, description) VALUES (2, 'Sports Officer',"The sports officer is in charge of managing the ECSS football team, and organising ECSS presence at football tournaments throughout the year.");