INSERT INTO electionType(electionName, electionDescription) VALUES('Postgrad and Masters Election', 'This is an election for Postgrad and Masters positions only.');
INSERT INTO electionType(electionName, electionDescription) VALUES('General Election', 'This is an election for most of the committee positions.');

INSERT INTO election(electionTypeID, nominationStartDate, nominationEndDate, votingStartDate, votingEndDate) VALUES(3, '2017-09-25', '2017-09-31', '2017-10-06', '2017-10-14');

INSERT INTO position(electionTypeID, positionName, description) VALUES(1, 'Postgraduate Representative', 'The PhD rep liases with students on ECS doctoral courses, helping the ECSS committee who are often in their undergraduate degrees to cater for the PhD audience.');
INSERT INTO position(electionTypeID, positionName, description) VALUES(1, 'Masters Representative', 'The masters rep liases with students on ECS masters courses, helping the ECSS committee who are often in their undergraduate degrees to cater for the masters audience.');

INSERT INTO electionType(electionName, electionDescription) VALUES('Charity Election', 'This is an election for ECSS''s charity of the year, which we raise awareness for.');
INSERT INTO position(electionTypeID, positionName, description) VALUES(3, 'ECSS Charity', 'This is our vote on which charity we should support for the current academic year.');

INSERT INTO nomination(positionID, electionID, nominationUsername, nominationName, image, manifesto) VALUES(3, 1, 'hb15g16', 'Special Effect', "../images/nominations/special-effect.jpg","<p>We put fun and inclusion back into the lives of people with physical disabilities by helping them to play video games.</p><p>By using technology ranging from modified joypads to eye-control, we're finding a way for people to play to the very best of their abilities.</p><p>But we're not just doing it for fun. By levelling the playing field, we're bringing families and friends together and having a profoundly positive impact on therapy, confidence and rehabilitation.</p>");
INSERT INTO nomination(positionID, electionID, nominationUsername, nominationName, image, manifesto) VALUES(3, 1, 'hb15g16', 'Get Well Gamers', "../images/nominations/getwellgamers.png","<p>Get Well Gamers UK is a <a href='https://www.oscr.org.uk/search-oscr/charity-details?number=SC046494'>charity</a> that takes donated video games and consoles to hospitals across the United Kingdom. Video games are an effective and proven pain management tool and provide much-needed entertainment for young people during long hospital stays. We are currently linked up with over 75 hospitals across the UK.</p>");
INSERT INTO nomination(positionID, electionID, nominationUsername, nominationName, image, manifesto) VALUES(3, 1, 'hb15g16', 'Rowans Hospice', "../images/nominations/rowans.jpg","<p>Rowans Hospice is dedicated to improving the lives of people living with life-limiting illnesses, their families and carers in Portsmouth and South East Hampshire.</p><p>We offer specialist support wherever it is needed, either at the Hospice, at home or within the local community.</p><p>As a charity, we couldn&rsquo;t provide these services without our fantastic supporters and volunteers who dedicate their time and money to help others.</p>");
INSERT INTO nomination(positionID, electionID, nominationUsername, nominationName, image, manifesto) VALUES(3, 1, 'hb15g16', 'S.C.R.A.T.C.H', "../images/nominations/scratch.jpg","<p>SCRATCH provides services which relieve the effects of hardship, disadvantage and poverty for individuals and families living in Southampton and the surrounding area.</p><p>You can find out more about all the projects we run in <a href='http://www.scratchcharity.co.uk/index.php?option=com_content&task=view&id=63&Itemid=98'>What We Do</a> , but here are a few examples:</p><p><a href='http://www.scratchcharity.co.uk/index.php?option=com_content&task=view&id=14&Itemid=28'>DORCAS Project</a> provides good quality furniture and household items</p><p><a href='http://www.scratchcharity.co.uk/index.php?option=com_content&task=view&id=24&Itemid=38'>CHRISTMAS COMPLETE</a> provides toys and gifts for youngsters who might go without</p><p><a href='http://www.scratchcharity.co.uk/index.php?option=com_content&task=view&id=28&Itemid=42'>COMMUNITY RE-PAINT</a> redistributes donated paint</p>");
INSERT INTO nomination(positionID, electionID, nominationUsername, nominationName, image, manifesto) VALUES(3, 1, 'hb15g16', 'Mencap', "../images/nominations/mencap.jpg","<p>Southampton Mencap is a voluntary organisation based in Portswood for children, young people and adults with a learning disability and their family carers. We work to raise awareness to their rights, alongside the direct provision of a range of services. We also take great pride in remaining small, local and strong. Alongside this we place a strong focus on working with other local agencies and the Local Authority to jointly improve the services available to our client group.</p>");
INSERT INTO nomination(positionID, electionID, nominationUsername, nominationName, image, manifesto) VALUES(3, 1, 'hb15g16', 'Solent Mind', "../images/nominations/solentmind.jpg","<p>We are Solent Mind, a registered charity providing a wide range of high quality services to support people with mental health problems across the Southern Region. Our trustees are responsible for governing our organisation, and delegate day-to-day operation to the Chief Executive and Senior Management Team. We set out our ambitions for the future clearly in our organisational business plan, which is supported by a range of strategic operational plans giving a clear vision for all our stakeholders.</p>");
INSERT INTO nomination(positionID, electionID, nominationUsername, nominationName, image, manifesto) VALUES(3, 1, 'hb15g16', 'Autism Hampshire', "../images/nominations/autism-hampshire.jpg","<p>Autism Hampshire was founded by the late Mr and Mrs Philip White MBE and a group of local parents of children with autism in Southampton in the mid-1960&rsquo;s.</p><p>Over the years the charity has worked hard to provide high quality services that meet the diverse need of people on the autism spectrum in Hampshire and the surrounding area. We are now proudly able to provide autism focused Training, Domiciliary Care, Supported Living services, Mentoring and a Community Access Team that responds to an average of 12,000 requests for help each year.</p>");
INSERT INTO nomination(positionID, electionID, nominationUsername, nominationName, image, manifesto) VALUES(3, 1, 'hb15g16', 'Practical Action', "../images/nominations/pa.png","<p>Practical Action is an international non-governmental organisation (NGO) that uses technology to challenge poverty in developing countries.</p><p><br />Programme work</p><p>Practical Action's projects are organised under four programme themes:</p><p><a href='https://practicalaction.org/energy'>Sustainable energy access</a><br /><a href='https://practicalaction.org/food'>Food and agriculture</a><br /><a href='https://practicalaction.org/urban-water-sanitation-waste'>Urban water and waste</a><br /><a href='https://practicalaction.org/disaster-risk-reduction'>Disaster risk reduction</a><br />Two cross-cutting themes are also present across our work:</p><p><a href='https://practicalaction.org/climate-change'>Climate change</a><br /><a href='https://practicalaction.org/markets-2'>Markets</a><br />&nbsp;</p><p>Where we work</p><p>The four programmes operate across our country and regional offices:</p><p><a href='https://practicalaction.org/bangladesh'>Bangladesh</a><br /><a href='https://practicalaction.org/east-africa'>East Africa (Kenya and Rwanda)</a><br /><a href='https://practicalaction.org/latin-america'>Latin America (Peru and Bolivia)</a><br /><a href='https://practicalaction.org/south-asia'>South Asia (Nepal, India and Sri Lanka)</a><br /><a href='https://practicalaction.org/southern-africa'>Southern Africa (Zimbabwe, Malawi, Zambia and Mozambique)</a><br /><a href='https://practicalaction.org/sudan'>Sudan</a><br /><a href='https://practicalaction.org/fr'>West Africa</a></p>");
